# Generated by Django 4.1.7 on 2024-04-15 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.BigAutoField(help_text='用户ID', primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(help_text='用户名', max_length=100, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(help_text='密码', max_length=128, verbose_name='密码')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=255, null=True, verbose_name='地址')),
                ('avatar', models.ImageField(blank=True, help_text='头像', null=True, upload_to='user/avatar/', verbose_name='头像')),
                ('user_type', models.IntegerField(choices=[(0, 'Admin'), (1, 'Merchant'), (2, 'User')], default=2, help_text='用户角色', verbose_name='用户角色')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'bikeshop_user',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('title', models.CharField(help_text='公告', max_length=200, verbose_name='公告')),
                ('content', models.TextField(help_text='公告内容', verbose_name='公告内容')),
                ('post_date', models.DateTimeField(auto_now_add=True, help_text='公告时间', verbose_name='公告时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'bikeshop_announcement',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='总价', max_digits=10, verbose_name='总价')),
                ('user_id', models.ForeignKey(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'bikeshop_cart',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('item_id', models.BigAutoField(help_text='商品ID', primary_key=True, serialize=False, verbose_name='商品ID')),
                ('item_name', models.CharField(help_text='商品名', max_length=100, verbose_name='商品名')),
                ('item_image', models.ImageField(blank=True, help_text='商品图片', null=True, upload_to='item/image/', verbose_name='商品图片')),
                ('item_quantity', models.IntegerField(default=0, help_text='用户角色', verbose_name='用户角色')),
                ('price', models.DecimalField(decimal_places=2, help_text='商品价格', max_digits=10, verbose_name='商品价格')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'bikeshop_item',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('item_type', models.CharField(choices=[('Road Frame', '公路车车架'), ('Road Wheel', '公路车车轮'), ('Road Tire', '公路车轮胎'), ('Road Brake', '公路车刹车系统'), ('Road Gear System', '公路车变速系统'), ('Road Drivetrain', '公路车传动系统'), ('Road Pedals', '公路车踏板'), ('Road Saddle', '公路车座椅'), ('Road Handlebars', '公路车车把'), ('Road Fork', '公路车前叉'), ('Road Rear Triangle', '公路车后叉'), ('Road Chain', '公路车链条'), ('Road Front Derailleur', '公路车前变速器'), ('Road Rear Derailleur', '公路车后变速器'), ('Road Bike', '公路车整车'), ('Hill Frame', '山地车车架'), ('Hill Wheel', '山地车车轮'), ('Hill Tire', '山地车轮胎'), ('Hill Brake', '山地车刹车系统'), ('Hill Gear System', '山地车变速系统'), ('Hill Drivetrain', '山地车传动系统'), ('Hill Pedals', '山地车踏板'), ('Hill Saddle', '山地车座椅'), ('Hill Handlebars', '山地车车把'), ('Hill Fork', '山地车前叉'), ('Hill Rear Triangle', '山地车后叉'), ('Hill Chain', '山地车链条'), ('Hill Front Derailleur', '山地车前变速器'), ('Hill Rear Derailleur', '山地车后变速器'), ('Hill Bike', '山地车整车')], help_text='商品类型', max_length=64, verbose_name='商品类型')),
            ],
            options={
                'verbose_name': '商品种类',
                'verbose_name_plural': '商品种类',
                'db_table': 'bikeshop_item_type',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('order_id', models.BigAutoField(help_text='订单号', primary_key=True, serialize=False, verbose_name='订单号')),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='下单时间', verbose_name='下单时间')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=255, null=True, verbose_name='地址')),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='总价', max_digits=10, verbose_name='总价')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'bikeshop_order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('orderdetail_id', models.BigAutoField(help_text='订单详情号', primary_key=True, serialize=False, verbose_name='订单详情号')),
                ('quantity', models.IntegerField(help_text='数量', verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, help_text='单价', max_digits=10, verbose_name='单价')),
                ('status', models.CharField(choices=[('tobepaid', '待支付'), ('pending', '订单准备中'), ('sent', '已发货'), ('shipping', '运送中'), ('delivered', '已送达'), ('confirmed', '已签收')], default='tobepaid', help_text='订单详情状态', max_length=64, verbose_name='订单详情状态')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.item')),
                ('merchant', models.ForeignKey(limit_choices_to={'user_type': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.order')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'db_table': 'bikeshop_order_detail',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(help_text='商品类型', on_delete=django.db.models.deletion.CASCADE, to='bike.itemtype', verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='item',
            name='merchant',
            field=models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('cartdetail_id', models.BigAutoField(help_text='购物车详情号', primary_key=True, serialize=False, verbose_name='购物车详情号')),
                ('quantity', models.IntegerField(default=0, help_text='数量', verbose_name='数量')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.cart')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.item')),
            ],
            options={
                'verbose_name': '购物车详情',
                'verbose_name_plural': '购物车详情',
                'db_table': 'bikeshop_cart_detail',
            },
        ),
    ]
