# Generated by Django 4.1.7 on 2024-04-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_alter_itemtype_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='item_type',
            field=models.CharField(choices=[('Road Frame', '公路车车架'), ('Road Wheel', '公路车车轮'), ('Road Tire', '公路车轮胎'), ('Road Brake', '公路车刹车系统'), ('Road Gear System', '公路车变速系统'), ('Road Freewheel ', '公路车飞轮'), ('Road Pedals', '公路车踏板'), ('Road Saddle', '公路车座椅'), ('Road Handlebars', '公路车车把'), ('Road Fork', '公路车前叉'), ('Road Chain', '公路车链条'), ('Road Bike', '公路车整车'), ('Hill Frame', '山地车车架'), ('Hill Wheel', '山地车车轮'), ('Hill Tire', '山地车轮胎'), ('Hill Brake', '山地车刹车系统'), ('Hill Gear System', '山地车变速系统'), ('Hill Freewheel ', '山地车飞轮'), ('Hill Pedals', '山地车踏板'), ('Hill Saddle', '山地车座椅'), ('Hill Handlebars', '山地车车把'), ('Hill Fork', '山地车前叉'), ('Hill Rear Suspension ', '山地车后避震器'), ('Hill Chain', '山地车链条'), ('Hill Bike', '山地车整车'), ('Others', '其他')], help_text='商品类型', max_length=64, unique=True, verbose_name='商品类型'),
        ),
    ]
