# Generated by Django 4.1.7 on 2024-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_alter_itemtype_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='电话', max_length=100, null=True, verbose_name='电话'),
        ),
    ]
