# Generated by Django 4.1.7 on 2024-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0007_item_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='comment',
            field=models.CharField(blank=True, help_text='评价', max_length=255, null=True, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(default=0, help_text='库存', verbose_name='库存'),
        ),
    ]
