# Generated by Django 4.1.7 on 2024-04-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0009_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, help_text='电话', max_length=100, null=True, verbose_name='电话'),
        ),
    ]
