# Generated by Django 4.1.7 on 2024-04-19 18:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0010_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('itemdesc_id', models.BigAutoField(help_text='商品详情ID', primary_key=True, serialize=False, verbose_name='商品详情ID')),
                ('desc_imgs', models.ImageField(blank=True, help_text='详情图', null=True, upload_to='item/description/', verbose_name='详情图')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.item')),
            ],
            options={
                'verbose_name': '商品详情',
                'verbose_name_plural': '商品详情',
                'db_table': 'bikeshop_item_desc',
            },
        ),
    ]
