# Generated by Django 4.1.7 on 2024-04-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0011_itemdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdescription',
            name='desc_imgs',
            field=models.CharField(blank=True, help_text='详情图', max_length=255, null=True, verbose_name='详情图'),
        ),
    ]
